import type { Metadata } from "next";
import './globals.css'
export const metadata: Metadata = {
  title: "Linux Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#0F1728]">
      <body className="">{children}</body>
    </html>
  );
}
